.DEFAULT_GOAL := compile

compile:
	@echo "Building"
	gcc -Wall -lm -o practical05 practical05.c
	gcc -Wall -lm -o practical05b practical05b.c

clean:
	@echo "Tidying up"
	rm practical05 practical05b

